name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.11.1
      - run: pnpm install

      - name: Run list
        run: pnpm test

      - name: Deploy
        if: ${{ github.event_name == 'push' && success() }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .
          CLEAN: true
