name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - name: Install modules
        run: yarn

      - name: Runs ESLint
        run: eslint . --cache --max-warnings=0

      - name: Runs StyleLint
        uses: actions-hub/stylelint@master
        env:
          INDENT_SPACES: "tab"