name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.11.1

      - run: pnpm install

      - run: pnpm test

      - name: Deploy
        if: ${{ github.event_name == 'push' && success() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          exclude_assets: '.github,node_modules,.eslintcache,package.json,pnpm-lock.yaml'
          publish_dir: .

      - name: Send Status to Discord
        if: ${{ github.event_name == 'push' && success() && contains(github.event.head_commit.message, '(Version ') }}
        uses: Ilshidur/action-discord@0.3.0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          args: 'Journal update has gone live.'
