name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 100

      - uses: actions/setup-node@main
        with:
          node-version: 20

      - uses: pnpm/action-setup@master
        with:
          version: 'latest'

      - run: pnpm install

      - run: pnpm test

      - name: Deploy
        if: ${{ github.event_name == 'push' && success() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          exclude_assets: '.github,node_modules,.eslintcache,package.json,pnpm-lock.yaml'
          publish_dir: .

      - name: Send Status to Discord
        if: ${{ github.event_name == 'push' && success() && contains(github.event.head_commit.message, '(Version ') }}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          args: 'Journal update has gone live.'

      # 3rd party hook
      - name: Send Status to Discord
        if: ${{ github.event_name == 'push' && success() && contains(github.event.head_commit.message, '(Version ') }}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK2 }}
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK2 }}
          args: 'Journal update has gone live. Visit <https://qartemist.github.io/JournalViewer> for the latest version.'
